### ISSUE TITLE
Testing Zip from Outside World - Failed!

### ISSUE THREAD

**Issue by Yushkun24** [bmx-ng/archive.mod#4]
I tried to open a zip file made by other compressing apps and it works so well on WinRAR, 7z, etc.. when extracting the files.
But when I'm going to extract it by using Mr.Brucey's zip mod.. the data is zero. I'm so afraid now to use this Mod. 😩

@Gwron can you please also try it!? Thanks, Mate!
The GitHub can't upload the file bcoz of its size. [https://www.mediafire.com/file/qn0ot5dgjsqfhu6/TestingZip.zip/file](url)

**Comment by Yushkun24** [comment]
![image](https://user-images.githubusercontent.com/98575740/152652016-4991048b-b3ef-42e6-9b0a-c99bca9421da.png)
![image](https://user-images.githubusercontent.com/98575740/152652025-3336871e-3d10-43d1-9057-a7f5044aa148.png)

**Comment by woollybah** [comment]
I doubt `LoadText()` is appropriate for most things, unless you are specifically wanting to load text from a text file.

`LoadBank()` appears to work fine..
```blitzmax
Local bank:TBank = LoadBank(ra.DataStream())
```

**Comment by Yushkun24** [comment]
It didn't work Mr.Brucey. :( Please fix the Mod and make it awesome! 🙏 Thank you.

![image](https://user-images.githubusercontent.com/98575740/152669682-8e0095d2-4aee-47d3-baab-4bc88176936a.png)
![image](https://user-images.githubusercontent.com/98575740/152669696-688482ba-90f6-44cc-9583-b74b045a2773.png)

**Comment by GWRon** [comment]
> https://www.mediafire.com/file/qn0ot5dgjsqfhu6/TestingZip.zip/file

```
[100%] Linking:TestingZipFromOutsideWorld
Executing:TestingZipFromOutsideWorld
File : WYSIWYG/
Size : 0
Type : Dir
String size   : 0
First n chars :
File : WYSIWYG/fix/
Size : 0
Type : Dir
String size   : 0
First n chars :
File : WYSIWYG/fix/WebBuilder.exe
Size : 20353024
Type : File
String size   : 20353024
First n chars : MZ


ÿÿ
¸
File : WYSIWYG/Readme _ password 123.txt
Size : 129
Type : File
String size   : 129
First n chars : Copy & Replace th
File : WYSIWYG/setup x64.exe
Size : 17982560
Type : File
String size   : 17982560
First n chars : MZP



ÿÿ
¸
```
